### ISSUE TITLE
educational qualification and experience needed for applying

### ISSUE THREAD

**Issue by Tusharmalik** [realslimshanky/Just-Jobs-Bot#1]
This is an opinion that employer should specify the educational qualification that is needed for the employees to apply for the job.

**Comment by realslimshanky** [comment]
That would be a good option to have on the bot. Would you like to implement this feature?

**Comment by Tusharmalik** [comment]
Sure but I will need help in order to implement it.

**Comment by realslimshanky** [comment]
Ping me in case you need any help.

**Comment by realslimshanky** [comment]
@Tusharmalik are you interested in working out a solution for this issue?

**Comment by Tusharmalik** [comment]
Busy now a days. Giving my internal exams. Will work on this after friday (8/9/17). @realslimshanky can you wait till that please.

**Comment by realslimshanky** [comment]
It's okay. Take your time.

**Comment by Tusharmalik** [comment]
Pull request has been made #3

**Comment by realslimshanky** [comment]
@Tusharmalik check the PR for the travis build.

**Comment by Tusharmalik** [comment]
I didn't get the problem with travis build. can u review it manually and correct it yourself.

**Comment by realslimshanky** [comment]
Sure, give me some time.
